name: Deploy to VPS

on:
  registry_package:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Run Container
        run: |
            echo "[+] Stopping old container"
            docker stop blog.germaniii.com || true
            docker rm blog.germaniii.com || true

            echo "[+] Pulling latest image"
            docker pull ${{ vars.BASE_URL }}/${{ vars.USER }}/blog.germaniii.com:latest

            echo "[+] Running new container"
            docker run -d \
              --name blog.germaniii.com \
              -p 8002:80 \
              --restart unless-stopped \
              ${{ vars.BASE_URL }}/${{ vars.USER }}/blog.germaniii.com:latest
